# Generated by Django 6.0.4 on 2026-05-31 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pessoal_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoal',
            options={'verbose_name': 'Perfil Pessoal', 'verbose_name_plural': 'Perfis Pessoais'},
        ),
        migrations.AddField(
            model_name='pessoal',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
