# Generated by Django 6.0.4 on 2026-05-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pessoal_options_pessoal_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoal',
            name='image',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
